version: "3.9"

services:
  app:
    build: "app/."
    ports:
      - "8080:8080"
      - "8081:8081"
  prometheus:
    build: "prometheus/."
    ports:
      - "9090:9090"
    depends_on:
      - "app"
  grafana:
    build: "grafana/."
    ports:
      - "3000:3000"
    depends_on:
      - "prometheus"