FROM grafana/grafana

ADD provisioning/datasources/prometheus.yml /etc/grafana/provisioning/datasources/
ADD provisioning/dashboards/default.yml /etc/grafana/provisioning/dashboards/
ADD provisioning/dashboards/dashboard.json /dashboards/

